IntegralEMRContextBundle_homepage:
    pattern:  /document/{uuid}
    defaults: { _controller: IntegralEMRContextBundle:Default:index }

Manage_Context:
    pattern:  /context_manager/
    defaults: { _controller: IntegralEMRContextBundle:Default:ContextBrowser }
  