IntegralEMRContextBundle_homepage:
    pattern:  /document/{uuid}
    defaults: { _controller: IntegralEMRContextBundle:Default:index }

Manage_Context:
    pattern:  /context_manager/
    defaults: { _controller: IntegralEMRContextBundle:Default:ContextBrowser }
    
Search_Keywords:
    pattern: /keywords/{keywords}/{code_type}
    defaults: { _controller: IntegralEMRContextBundle:AjaxSearch:SearchKeyword }
    
Search_document_sections:
  pattern: /section/{keywords}
  defaults: { _controller: IntegralEMRContextBundle:AjaxSearch:SearchDocsec,keywords: "Physical Exam" }
    