parameters:
#    integral_emr_context.example.class: IntegralEMR\ContextBundle\Example

services:
#    integral_emr_context.example:
#        class: %integral_emr_context.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
